---
name: CI

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan workflow call:
  workflow_call:
  # Scan mainline branches and report all findings:
  push:
    branches: ["main"]
  # Scan changed files in PRs (diff-aware scanning):
  pull_request:
    branches: ["main"]

# Don't grant any access by default
permissions: {}

env:
  TARGET_REF: ${{ github.head_ref || github.ref_name }}
  GO111MODULE: on
  GOPRIVATE: ""
  APP: "co-pilot-reporting"
  COV: "./coverage"
  GCOV: "./coverage.gcov"
  LCOV: "./coverage.lcov"
  VPATH: "github.com/gdcorp-engineering/co-pilot-reporting/internal/version"

jobs:
  ci:
    name: ci

    strategy:
      matrix:
        go-version: ['stable']  # only use ONE version of go here or the upload-artifact will fail

    runs-on:
      labels:
        - self-hosted
        - 6909-githubadmintools

    ############################################
    # Grant minimal permissions
    ############################################
    permissions:
      contents: read
      statuses: write

    steps:
      - name: actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          # Needed to get tags for versioning
          fetch-depth: 0

      - name: actions/setup-go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34  # v5.3.0
        with:
          go-version: ${{ matrix.go-version }}

      # nslookup
      - name: nslookup
        shell: bash
        run: |
          set -x
          nslookup cds-api.int.gdcorp.tools

      # Show the Go environment
      - name: report go environment
        shell: bash
        run: |
          set -x
          go version
          go env
          go clean --cache
          go mod tidy

      - name: golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae  # v6.2.0
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the
          # latest version. When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash
          # of a commit.
          version: latest

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"

          # Optional: When using only-new-issues option, the GitHub API is used, so a token is required.
          # github-token:

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues:

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          #
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0
          args: --verbose
            --tests=true
            --timeout=6m
            --config=.github/linters/.golangci.yml
            --issues-exit-code=1

          # Optional: Force the usage of the embedded problem matchers.
          # problem-matchers: true

          # Optional: If set to true, then all caching functionality will be completely
          # disabled, takes precedence over all other caching options.
          # skip-cache: true

          # Optional: If set to true, caches will not be saved, but they may still be
          # restored, required skip-cache: false.
          # skip-save-cache: true

          # Optional: Periodically invalidate the cache every cache-invalidation-interval
          # days to ensure that outdated data is removed and fresh data is loaded.
          # cache-invalidation-interval: 7

      - name: pre-build
        id: prebuild
        shell: bash
        run: |
          set -x
          echo "pre-building"
          appversion=$(git describe --tags | awk '{gsub(/ /, "_"); print}')
          buildtime=$(date -u "+%Y-%m-%dT%TZ")
          goversion=$(go version | awk '{gsub(/ /, "_"); print}')
          echo "GLDFLAGS=-s -w -X=${VPATH}.AppVersion=${appversion} -X=${VPATH}.Branch=${GITHUB_REF} -X=${VPATH}.BuildTime=${buildtime} -X=${VPATH}.Commit=${{ github.sha }} -X=${VPATH}.GoVersion=${goversion}" >> "$GITHUB_ENV"

      - name: go build
        shell: bash
        env:
          APP_NAME: ${{ env.APP }}
          GLDFLAGS: ${{ env.GLDFLAGS }}
          TARGET_DIR: dist
        run: |
          set -x
          go env
          mkdir "$TARGET_DIR"
          go build -x -v -ldflags="${GLDFLAGS}" \
            -o "$TARGET_DIR/$APP_NAME" "cmd/$APP_NAME/main.go"
          "$TARGET_DIR/$APP_NAME" -version

      - name: go test
        shell: bash
        run: |
          go env
          go test -v -race -coverprofile="$GCOV" -covermode=atomic ./...
          go test -v -coverprofile="$GCOV" -covermode=count ./...
          go tool cover -func="$GCOV" -o="$COV.out"

      - name: jandelgado/gcov2lcov-action
        uses: jandelgado/gcov2lcov-action@4e1989767862652e6ca8d3e2e61aabe6d43be28b  # v1.1.1
        with:
          infile: ${{ env.GCOV }}
          outfile: ${{ env.LCOV }}

      - name: VeryGoodOpenSource/very_good_coverage
        uses: VeryGoodOpenSource/very_good_coverage@c953fca3e24a915e111cc6f55f03f756dcb3964c  # v3.0.0
        with:
          path: ${{ env.LCOV }}
          min_coverage: 0

      # Upload generated artifacts for historical reference
      - name: actions/upload-artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: test-reports
          path: ${{ env.COV }}.*
          retention-days: 90

      - name: Show Artifact ID
        shell: bash
        run: |
          echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
